services:

  - type: worker
    name: homeDYbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python homeDnYtrade.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false